let words = [
    "bell",
    "roar",
    "noise",
    "softly",
    "winked",
    "sound",
    "thought",
    "another",
    "problem",
    "suddenly",
    "a grizzly bear",
    "rumbling thunder",
    "gave me a look",
    "great white shark",
    "hit me like a punch",
    "toes",
    "head",
    "huge",
    "little",
    "scary",
    "listen",
    "quiet",
    "hungry",
    "through",
    "grumble",
    "jumped up",
    "wildlife park",
    "eat your lunch",
    "seemed to echo",
    "something in the air",
    "stall",
    "learn",
    "school",
    "father",
    "parents",
    "replied",
    "students",
    "principal",
    "afternoon",
    "celebrate",
    "of course",
    "thank you",
    "next week",
    "coffee shop",
    "with a smile",
    "help",
    "then",
    "make",
    "tossed",
    "friends",
    "arrived",
    "spread",
    "flipped",
    "excited",
    "everyone",
    "let it sizzle",
    "crack an egg",
    "crowded around",
    "pound and knead",
    "stretch out the dough",
    "tide",
    "snail",
    "turtle",
    "crab",
    "clam",
    "same",
    "otters",
    "lobster",
    "oysters",
    "mussels",
    "tortoise",
    "scallops",
    "shellfish",
    "sea",
    "urchin",
    "a pod of whales",
    "raft",
    "most",
    "float",
    "picnic",
    "beach",
    "ocean",
    "usually",
    "habitat",
    "journey",
    "lifebuoy",
    "seashore",
    "creatures",
    "diving board",
    "a shoal of fish",
    "a school of dolphins",
    "grew",
    "strong",
    "squirm",
    "leaves",
    "insects",
    "nectar",
    "branch",
    "tongue",
    "eggshell",
    "hatches",
    "life cycle",
    "beautiful",
    "caterpillar",
    "in a few hours",
    "after some time",
    "feeling",
    "beetle",
    "fertiliser",
    "attracted",
    "crumpled",
    "thorax",
    "flowers",
    "flutters",
    "colourful",
    "vegetables",
    "pupa stage",
    "butterfly park",
    "wind blowing",
    "a pair of wings",
    "hot and sunny day"
  ];